# Generated by Django 2.0.6 on 2018-06-02 12:47

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('match_id', models.BigIntegerField()),
                ('duration', models.IntegerField()),
                ('first_blood_time', models.IntegerField()),
                ('game_mode', models.CharField(max_length=25)),
                ('user_win', models.BooleanField()),
                ('patch', models.IntegerField()),
                ('region', models.IntegerField()),
                ('user_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
