# Generated by Django 2.0.6 on 2018-06-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='user_data',
            new_name='player_data',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='user_win',
            new_name='radiant_win',
        ),
    ]
