# Generated by Django 2.0.6 on 2018-06-07 14:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20180607_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='player_data',
        ),
        migrations.AddField(
            model_name='match',
            name='dire',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='radiant',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
